#cloud-config
rancher:
  console: centos
  network:
    dns:
      search:
      - 8.8.8.8
      - 8.8.4.4
runcmd:
  - yum install -q -y man zsh git
  - chsh -s /bin/zsh rancher
  - su - rancher -c 'git clone --depth=1 git@github.com:eexit/rancheros.git'
  - /home/rancher/rancheros/root/provision
  - su - rancher -c '~/rancheros/home/rancher/provision'
