#!/bin/sh
set -euo pipefail
cwd=$(dirname "$0")

echo -n "oh-my-zsh... "
git clone --depth=1 https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
curl -fsSL https://raw.githubusercontent.com/shashankmehta/dotfiles/master/thesetup/zsh/.oh-my-zsh/custom/themes/gitster.zsh-theme -o ~/gitster.zsh-theme
mv -f ~/gitster.zsh-theme ~/.oh-my-zsh/themes
mv -f "$cwd/.zshrc" ~/.zshrc
echo "ok"

echo -n "git... "
git clone --depth=1 https://github.com/eexit/dotfiles.git ~/.dotfiles
sed -e "s/AUTHORNAME/Joris Berthelot/g" -e "s/AUTHOREMAIL/admin@eexit.net/g" -e "s/GIT_CREDENTIAL_HELPER/cache/g" ~/.dotfiles/git/gitconfig.local.symlink.example > ~/.gitconfig.local
ln -s ~/.dotfiles/git/gitconfig.symlink ~/.gitconfig
ln -s ~/.dotfiles/vim/vimrc.symlink ~/.vimrc
echo "ok"
