version: '3.6'
services:
  proxy:
    build: .
    container_name: proxy
    network_mode: bridge
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - proxy:/usr/share/nginx/html
      - proxy:/etc/nginx/vhost.d
      - proxy:/etc/nginx/certs
      - ./vhost.d/blog.eexit.net_location:/etc/nginx/vhost.d/blog.test_location
      - ./vhost.d/joris.berthelot.photography_location:/etc/nginx/vhost.d/portfolio.test_location
volumes:
  proxy:
