version: '3.6'
services:
  proxy:
    build: .
    container_name: proxy
    network_mode: bridge
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /usr/share/nginx/html
      - ./certs:/etc/nginx/certs
      - ./vhosts/blog.eexit.net_location:/etc/nginx/vhost.d/blog.test_location
  lec:
    image: jrcs/letsencrypt-nginx-proxy-companion
    network_mode: bridge
    environment:
      NGINX_PROXY_CONTAINER: proxy
    depends_on:
      - proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
