version: '3.6'
x-logging:
  &default-logging
  driver: json-file
  options:
    max-size: 200k
    max-file: '10'
services:
  proxy:
    build: .
    image: proxy:${DATE}
    container_name: proxy
    network_mode: bridge
    logging: *default-logging
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - proxy-conf:/etc/nginx/conf.d
      - proxy-vhost:/etc/nginx/vhost.d
      - proxy-html:/usr/share/nginx/html
      - proxy-certs:/etc/nginx/certs:ro
  lec:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: lec
    logging: *default-logging
    network_mode: bridge
    restart: unless-stopped
    environment:
      NGINX_PROXY_CONTAINER: proxy
    depends_on:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - proxy-conf:/etc/nginx/conf.d
      - proxy-vhost:/etc/nginx/vhost.d
      - proxy-html:/usr/share/nginx/html
      - proxy-certs:/etc/nginx/certs
volumes:
  proxy-conf:
  proxy-vhost:
  proxy-html:
  proxy-certs:
