#!/bin/sh
set -euo pipefail
cwd=$(dirname "$0")

echo -n "iptable-restore... "
iptables-restore --noflush < "$cwd/iptables.rules"
echo "ok"

echo -n "docker-compose... "
mkdir -p /opt/bin
COMPOSE_VERSION=`curl -s https://api.github.com/repos/docker/compose/releases/latest | grep 'tag_name' | cut -d\" -f4`
sh -c "curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > /opt/bin/docker-compose"
chown -R rancher:root /opt/bin
chmod -R +x /opt/bin
echo "ok"

echo -n "motd... "
cp -f "$cwd/../etc/motd" /etc/motd
chown root:root /etc/motd
chmod 0644 /etc/motd
echo "ok"
